server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/user?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: user
    password: 1247
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: 192.168.0.46:9092

  jwt:
    expires-in: 86400 # 1day
    mobile-expires-in: 31536000
    table-expires-in: 31536000
    secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86G