apiVersion: v1
kind: Service
metadata:
  name: k8s-backend-gateway-lb
spec:
  type: LoadBalancer
  selector:
    app: k8s-backend-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30080