apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backend-user
  template:
    metadata:
      labels:
        app: k8s-backend-user
    spec:
      containers:
        - name: k8s-backend-user
          image: zhiyin22/k8s-backend-user:0.0.5
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: server.port
              valueFrom:
                configMapKeyRef:
                  name: backend-us
                  key: server.port
          ports:
            - containerPort: 8080

          volumeMounts:
            - mountPath: /etc/config
              name: backend-user-config-volume
      volumes:  #  컨테이너와 같은 레벨이어야 함
        - name: backend-user-config-volume
          configMap:
            name: backend-user-config
            items:
              - key: application-dev.yml
                path: application-dev.yml


